### ISSUE TITLE
Error loading colours when installed via Package Manager 

### ISSUE THREAD

**Issue by noma4i** [thenewvu/SublimeReviewMyself#1]
1. Install via Package Manager
2. Error loading syntax file "Packages/ReviewMyself/ReviewMyself.tmLanguage": Unable to open Packages/ReviewMyself/ReviewMyself.tmLanguage

Plugin is working but colours are just white background and black text.

**Comment by realmikebutler** [comment]
Yep same here, spews a bunch of alerts about missing NeonDark.hidden-tmTheme.  Otherwise seems quite handy.

**Comment by thenewvu** [comment]
Fixed in v1.1.1. Thanks so much. Please help me recheck and confirm.
