### ISSUE TITLE
Suggestion : Add only_dir_path  property

### ISSUE THREAD

**Issue by isyara** [thenewvu/SublimeReviewMyself#2]
I'm under CMS and i'm working intro specific folder i do not want  track todo from core / plugin of CMS  but only specific directories  with  

exemple with Drupal :

/
/modules
/sites/all/themes
/sites/all/default
/sites/all/modules
etc...

I would like use MyReview **only for this directories**  (included sub dir) :

"only_dir_path" :  ["/sites/all/themes/my_website" , "/sites/all/modules/my_modules"]

**Comment by thenewvu** [comment]
@isyara: Thanks for the suggestion. I implemented the feature in v3.1.0.
Please read the below file for usage:
https://github.com/thenewvu/SublimeReviewMyself/blob/master/messages/3.1.0.txt
